import {NextResponse} from "next/server";
import {getPool,requireAdmin} from "@/lib/server/db";
import {decryptSecret} from "@/lib/server/crypto";
export const runtime="nodejs";
export async function GET(request:Request){try{requireAdmin(request);const {rows}=await getPool().query("SELECT id,title,agenda,status,summary,created_at FROM meetings ORDER BY created_at DESC LIMIT 50");return NextResponse.json({meetings:rows});}catch(e){const m=e instanceof Error?e.message:"Internal error";return NextResponse.json({error:m},{status:m==="UNAUTHORIZED"?401:503});}}
export async function POST(request:Request){const pool=getPool();let meetingId:string|undefined;try{requireAdmin(request);const b=await request.json();const title=String(b.title||"Meeting").trim(),agenda=String(b.agenda||"").trim(),participants=Array.isArray(b.participants)?[...new Set(b.participants.map((x:unknown)=>String(x)))]:[];const maxRounds=Math.min(2,Math.max(1,Number(b.maxRounds)||1));if(!agenda||agenda.length>5000||participants.length<1||participants.length>6)return NextResponse.json({error:"Agenda wajib diisi dan peserta harus 1–6 karyawan."},{status:400});
const created=await pool.query("INSERT INTO meetings(title,agenda,status) VALUES($1,$2,'running') RETURNING id",[title,agenda]);meetingId=created.rows[0].id;
await pool.query("INSERT INTO office_events(event_type,status,message,metadata) VALUES('meeting_started','working',$1,$2::jsonb)",["Meeting dimulai: "+title,JSON.stringify({meetingId,participants})]);
const roster=await pool.query("SELECT e.id,e.name,e.role,e.system_prompt,e.personality,COALESCE(e.model_id,p.default_model) AS model_id,p.id AS provider_id,p.base_url,p.api_format,c.encrypted_token FROM employees e LEFT JOIN providers p ON p.id=e.provider_id AND p.enabled=true LEFT JOIN provider_credentials c ON c.provider_id=p.id WHERE e.id=ANY($1::text[]) AND e.enabled=true",[participants]);
if(roster.rows.length!==participants.length)throw new Error("Satu atau lebih peserta tidak ditemukan atau nonaktif.");
const contributions:Array<{employeeId:string;name:string;content:string;model:string}>=[];
for(let round=1;round<=maxRounds;round++){for(const e of roster.rows){if(!e.provider_id||!e.encrypted_token||!e.model_id)throw new Error(`Karyawan ${e.name} belum dikonfigurasi dengan provider/token/model.`);
const previous=contributions.map(c=>`${c.name}: ${c.content}`).join("\n\n").slice(-12000);
const prompt=`Meeting: ${title}\nAgenda: ${agenda}\nPutaran: ${round}/${maxRounds}\nKontribusi peserta sejauh ini:\n${previous||"(belum ada)"}\nBerikan analisis singkat yang relevan. Tanggapi ide peserta lain bila ada. Jangan mengklaim melakukan tindakan eksternal. Jika tindakan penting diperlukan, minta persetujuan Bos Angga.`;
const url=e.base_url.replace(/\/$/,"")+(e.api_format==="openai-responses"?"/responses":"/chat/completions");const token=decryptSecret(e.encrypted_token);
const payload=e.api_format==="openai-responses"?{model:e.model_id,input:[{role:"system",content:e.system_prompt+" Kepribadian: "+e.personality},{role:"user",content:prompt}]}:{model:e.model_id,messages:[{role:"system",content:e.system_prompt+" Kepribadian: "+e.personality},{role:"user",content:prompt}],max_tokens:500};
const resp=await fetch(url,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(payload),signal:AbortSignal.timeout(45000)});const raw=await resp.text();let data:any;try{data=JSON.parse(raw)}catch{data={}};if(!resp.ok)throw new Error(`Provider untuk ${e.name} gagal HTTP ${resp.status}: ${String(data.error?.message||raw).slice(0,200)}`);
const content=e.api_format==="openai-responses"?(data.output_text||data.output?.flatMap((x:any)=>x.content||[]).map((x:any)=>x.text||"").join("")):data.choices?.[0]?.message?.content;if(!content)throw new Error(`Respons kosong dari ${e.name}`);
await pool.query("INSERT INTO meeting_messages(meeting_id,employee_id,content) VALUES($1,$2,$3)",[meetingId,e.id,content]);contributions.push({employeeId:e.id,name:e.name,content,model:e.model_id});await pool.query("INSERT INTO usage_records(provider_id,employee_id,model_id,prompt_tokens,completion_tokens,status,duration_ms) VALUES($1,$2,$3,$4,$5,'success',NULL)",[e.provider_id,e.id,e.model_id,data.usage?.prompt_tokens??data.usage?.input_tokens??null,data.usage?.completion_tokens??data.usage?.output_tokens??null]);}}
const summary=contributions.map(c=>c.name+": "+c.content).join("\n\n");await pool.query("UPDATE meetings SET status='completed',summary=$2 WHERE id=$1",[meetingId,summary]);await pool.query("INSERT INTO office_events(event_type,status,message,metadata) VALUES('meeting_completed','completed',$1,$2::jsonb)",["Meeting selesai: "+title,JSON.stringify({meetingId,contributions:contributions.length})]);return NextResponse.json({meetingId,title,rounds:maxRounds,contributions});
}catch(e){const m=e instanceof Error?e.message:"Internal error";if(meetingId)await pool.query("UPDATE meetings SET status='completed',summary=$2 WHERE id=$1",[meetingId,"Meeting tidak selesai: "+m]).catch(()=>{});return NextResponse.json({error:m,meetingId},{status:m==="UNAUTHORIZED"?401:502});}}
