"use client";
import {useCallback,useEffect,useState} from "react";
type Provider={id:string;name:string;base_url:string;api_format:string;default_model:string|null;enabled:boolean;has_token:boolean};
type Model={id:string;name:string};
type Employee={id:string;name:string;role:string;provider_id:string|null;model_id:string|null;provider_name:string|null};
type Approval={id:string;action_type:string;description:string;status:string;created_at:string};
const css=`*{box-sizing:border-box}body{margin:0;background:#080d15;color:#edf3fb;font-family:Inter,system-ui,Arial;overflow:auto!important;height:auto;min-height:100vh}button,input,select,textarea{font:inherit}button{cursor:pointer}.wrap{max-width:1200px;margin:auto;padding:24px}.muted{color:#91a0b3;font-size:13px}.card{background:#0e1622;border:1px solid #263449;border-radius:16px;padding:18px;margin:14px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:12px}.field{display:grid;gap:6px;margin:10px 0}.field label{font-size:12px;color:#a9b7c9}.field input,.field select,.field textarea{background:#080d15;color:#edf3fb;border:1px solid #34435a;border-radius:9px;padding:10px;width:100%}.btn{background:#dce9ff;color:#0a1423;border:0;border-radius:9px;padding:10px 13px;font-weight:700;margin:5px 5px 5px 0}.btn.alt{background:#1b2a40;color:#dce9ff;border:1px solid #334760}.btn:disabled{opacity:.5;cursor:wait}.status{white-space:pre-wrap;background:#08111b;border-radius:9px;padding:10px;font-size:12px;margin-top:8px}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.tag{font-size:11px;background:#1c2b40;padding:5px 8px;border-radius:99px}.chat{height:280px;overflow:auto;background:#080d15;border:1px solid #263449;border-radius:10px;padding:12px;white-space:pre-wrap}.msg{padding:10px;border-bottom:1px solid #202b3a}.msg b{color:#8fb7ff}.top{display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}h1{margin-bottom:4px}h2{font-size:18px}`;
export default function ControlPage(){
 const [admin,setAdmin]=useState("");const [providers,setProviders]=useState<Provider[]>([]);const [models,setModels]=useState<Record<string,Model[]>>({});const [employees,setEmployees]=useState<Employee[]>([]);const [approvals,setApprovals]=useState<Approval[]>([]);const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);
 const [name,setName]=useState("9Router");const [baseUrl,setBaseUrl]=useState("http://127.0.0.1:20128/v1");const [apiFormat,setApiFormat]=useState("openai-chat");const [defaultModel,setDefaultModel]=useState("");const [token,setToken]=useState("");
 const [employeeId,setEmployeeId]=useState("raka");const [providerId,setProviderId]=useState("");const [modelId,setModelId]=useState("");const [message,setMessage]=useState("");const [answer,setAnswer]=useState("");const [conversationId,setConversationId]=useState<string|null>(null);
 const [meetingTitle,setMeetingTitle]=useState("Perencanaan proyek");const [agenda,setAgenda]=useState("");const [participants,setParticipants]=useState("raka,sinta,andi,bima");const [meetingResult,setMeetingResult]=useState("");
 const [approvalType,setApprovalType]=useState("external_side_effect");const [approvalDescription,setApprovalDescription]=useState("");
 const headers={Authorization:"Bearer "+admin,"Content-Type":"application/json"};
 const call=useCallback(async(path:string,init:RequestInit={})=>{const r=await fetch(path,{...init,headers:{...headers,...(init.headers||{})}});const data=await r.json().catch(()=>({error:"Respons bukan JSON"}));if(!r.ok)throw new Error(data.error||"HTTP "+r.status);return data;},[admin]);
 const refresh=useCallback(async()=>{if(!admin)return;try{const [p,e,a]=await Promise.all([call("/api/providers"),call("/api/employees"),call("/api/approvals")]);setProviders(p.providers||[]);setEmployees(e.employees||[]);setApprovals(a.approvals||[]);setStatus("Data berhasil dimuat dari backend.");}catch(e){setStatus(e instanceof Error?e.message:String(e));}},[admin,call]);
 useEffect(()=>{if(admin)void refresh();},[admin,refresh]);
 async function action(fn:()=>Promise<void>){setBusy(true);try{await fn()}catch(e){setStatus(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function createProvider(){await action(async()=>{const r=await call("/api/providers",{method:"POST",body:JSON.stringify({name,baseUrl,apiFormat,defaultModel:defaultModel||null,token})});setToken("");setStatus("Provider tersimpan dengan ID "+r.provider.id);await refresh()})}
 async function testProvider(id:string){await action(async()=>{const r=await call("/api/providers/"+id+"/test",{method:"POST",body:"{}"});setStatus("Tes koneksi: "+(r.ok?"BERHASIL":"GAGAL")+" — "+(r.message||r.error)+" HTTP "+r.status)})}
 async function syncModels(id:string){await action(async()=>{const r=await call("/api/providers/"+id+"/models",{method:"POST",body:"{}"});setModels(x=>({...x,[id]:r.models||[]}));setStatus("Daftar model diperbarui: "+r.count+" model.")})}
 async function assign(){await action(async()=>{await call("/api/employees",{method:"PATCH",body:JSON.stringify({id:employeeId,providerId,modelId})});setStatus("Model karyawan tersimpan.");await refresh()})}
 async function sendChat(){await action(async()=>{const r=await call("/api/chat",{method:"POST",body:JSON.stringify({employeeId,message,conversationId})});setConversationId(r.conversationId);setAnswer(r.answer);setMessage("");setStatus("Respons nyata diterima dari model "+r.model+". Token input/output: "+(r.usage.prompt_tokens??"tidak tersedia")+"/"+(r.usage.completion_tokens??"tidak tersedia"));})}
 async function runMeeting(){await action(async()=>{const r=await call("/api/meetings",{method:"POST",body:JSON.stringify({title:meetingTitle,agenda,participants:participants.split(",").map(x=>x.trim()).filter(Boolean),maxRounds:2})});setMeetingResult(JSON.stringify(r,null,2));setStatus("Meeting disimpan. Peserta yang gagal tetap tercatat pada hasil.");})}
 async function createApproval(){await action(async()=>{const r=await call("/api/approvals",{method:"POST",body:JSON.stringify({actionType:approvalType,description:approvalDescription,payload:{requestedBy:"Bos Angga"}})});setStatus("Permintaan persetujuan dibuat: "+r.approval.id);setApprovalDescription("");await refresh()})}
 async function decideApproval(id:string,decision:"approved"|"rejected"){await action(async()=>{await call("/api/approvals/"+id,{method:"PATCH",body:JSON.stringify({decision})});setStatus("Keputusan persetujuan tersimpan.");await refresh()})}
 return <main className="wrap"><style>{css}</style><div className="top"><div><div className="tag">KARYAWAN AI · CONTROL ROOM</div><h1>Provider, Agent & Meeting Control</h1><p className="muted">Token admin hanya disimpan dalam memori tab ini. API key provider disimpan terenkripsi di PostgreSQL.</p></div><a href="/" className="tag">Kembali ke kantor 3D ↗</a></div>
 <section className="card"><h2>1. Hubungkan panel ke backend lokal</h2><div className="field"><label>KAI_ADMIN_TOKEN (tidak disimpan di browser)</label><input type="password" value={admin} onChange={e=>setAdmin(e.target.value)} placeholder="Tempel token admin dari .env.local"/></div><button className="btn" disabled={!admin||busy} onClick={()=>void refresh()}>Muat data backend</button><div className="status">{status||"Masukkan token admin untuk memuat data PostgreSQL."}</div></section>
 <section className="card"><h2>2. Tambah provider</h2><div className="grid"><div className="field"><label>Nama provider</label><input value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><label>Base URL API</label><input value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} placeholder="http://127.0.0.1:20128/v1"/></div><div className="field"><label>Format API</label><select value={apiFormat} onChange={e=>setApiFormat(e.target.value)}><option value="openai-chat">OpenAI-compatible Chat Completions</option><option value="openai-responses">OpenAI Responses API</option></select></div><div className="field"><label>Model default (opsional)</label><input value={defaultModel} onChange={e=>setDefaultModel(e.target.value)} placeholder="Isi setelah sinkronisasi model"/></div><div className="field"><label>API token</label><input type="password" autoComplete="new-password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Token provider; hanya dikirim ke backend"/></div></div><button className="btn" disabled={!admin||busy||!token.trim()} onClick={()=>void createProvider()}>Simpan provider</button></section>
 <section className="card"><h2>3. Provider tersimpan</h2>{!providers.length?<p className="muted">Belum ada provider di database, atau data belum dimuat.</p>:<div className="grid">{providers.map(p=><article className="card" key={p.id}><div className="row"><b>{p.name}</b><span className="tag">{p.has_token?"Token tersimpan":"Token belum ada"}</span></div><p className="muted">{p.base_url}</p><p className="muted">Format: {p.api_format} · Default: {p.default_model||"belum diatur"}</p><button className="btn alt" disabled={!admin||busy} onClick={()=>void testProvider(p.id)}>Tes koneksi nyata</button><button className="btn" disabled={!admin||busy} onClick={()=>void syncModels(p.id)}>Sinkronkan model</button>{models[p.id]?.length>0&&<div className="field"><label>Model ditemukan ({models[p.id].length})</label><select value={providerId===p.id?modelId:""} onChange={e=>{setProviderId(p.id);setModelId(e.target.value);setDefaultModel(e.target.value)}}><option value="">Pilih model untuk penetapan</option>{models[p.id].map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></div>}</article>)}</div>}</section>
 <section className="card"><h2>4. Tetapkan provider dan model untuk karyawan</h2><div className="grid"><div className="field"><label>Karyawan</label><select value={employeeId} onChange={e=>setEmployeeId(e.target.value)}>{employees.map(e=><option key={e.id} value={e.id}>{e.name} — {e.role}</option>)}</select></div><div className="field"><label>Provider</label><select value={providerId} onChange={e=>{setProviderId(e.target.value);setModelId("")}}><option value="">Pilih provider</option>{providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="field"><label>Model ID persis dari hasil sinkronisasi</label><select value={modelId} onChange={e=>setModelId(e.target.value)}><option value="">Pilih model</option>{(models[providerId]||[]).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></div></div><button className="btn" disabled={!admin||busy||!providerId||!modelId} onClick={()=>void assign()}>Simpan penetapan karyawan</button><div className="grid">{employees.map(e=><div className="side-item" key={e.id}><b>{e.name} · {e.role}</b><p className="muted">{e.provider_name||"Belum ada provider"} / {e.model_id||"Belum ada model"}</p></div>)}</div></section>
 <section className="card"><h2>5. Chat AI agent nyata</h2><div className="field"><label>Pilih karyawan</label><select value={employeeId} onChange={e=>setEmployeeId(e.target.value)}>{employees.map(e=><option key={e.id} value={e.id}>{e.name} — {e.role}</option>)}</select></div><div className="chat">{answer||"Respons model akan muncul di sini. Percakapan sebelumnya tersimpan di PostgreSQL."}</div><div className="field"><label>Pesan</label><textarea rows={3} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Tulis instruksi untuk karyawan..." /></div><button className="btn" disabled={!admin||busy||!message.trim()} onClick={()=>void sendChat()}>Kirim ke AI</button><button className="btn alt" onClick={()=>{setConversationId(null);setAnswer("")}}>Percakapan baru</button></section>
 <section className="card"><h2>6. Meeting antar-agent (maksimal dua putaran)</h2><div className="grid"><div className="field"><label>Judul</label><input value={meetingTitle} onChange={e=>setMeetingTitle(e.target.value)}/></div><div className="field"><label>Peserta (ID dipisah koma)</label><input value={participants} onChange={e=>setParticipants(e.target.value)} placeholder="raka,sinta,andi,bima"/></div></div><div className="field"><label>Agenda</label><textarea rows={3} value={agenda} onChange={e=>setAgenda(e.target.value)} placeholder="Tujuan rapat dan konteks..."/></div><button className="btn" disabled={!admin||busy||!agenda.trim()} onClick={()=>void runMeeting()}>Mulai meeting nyata</button>{meetingResult&&<pre className="status">{meetingResult}</pre>}</section>
 <section className="card"><h2>7. Persetujuan Bos Angga</h2><div className="grid"><div className="field"><label>Jenis tindakan</label><select value={approvalType} onChange={e=>setApprovalType(e.target.value)}><option value="external_side_effect">Tindakan eksternal</option><option value="github_push">Push GitHub</option><option value="file_write">Menulis file</option><option value="deployment">Deployment</option><option value="data_delete">Menghapus data</option></select></div><div className="field"><label>Deskripsi tindakan</label><input value={approvalDescription} onChange={e=>setApprovalDescription(e.target.value)} placeholder="Jelaskan tindakan yang diminta"/></div></div><button className="btn" disabled={!admin||busy||!approvalDescription.trim()} onClick={()=>void createApproval()}>Buat permintaan persetujuan</button>{approvals.map(a=><div className="side-item" key={a.id}><div className="row"><b>{a.action_type}</b><span className="tag">{a.status}</span></div><p>{a.description}</p>{a.status==="pending"&&<><button className="btn" disabled={busy} onClick={()=>void decideApproval(a.id,"approved")}>Setujui</button><button className="btn alt" disabled={busy} onClick={()=>void decideApproval(a.id,"rejected")}>Tolak</button></>}</div>)}</section>
 <p className="muted">Catatan: persetujuan di sini mencatat keputusan. Itu tidak otomatis menjalankan push, deployment, penghapusan, atau eksekusi shell; setiap integrasi eksekusi perlu pemeriksaan izin tambahan.</p></main>
}
