"use client";
import {useEffect,useState} from "react";
type Provider={id:string;name:string;baseUrl:string;apiFormat:string;defaultModel:string|null;enabled:boolean;models:{modelId:string;available:boolean}[];hasCredential:boolean};
export default function ProvidersPage(){
 const [providers,setProviders]=useState<Provider[]>([]),[name,setName]=useState("9Router"),[baseUrl,setBaseUrl]=useState("http://127.0.0.1:20128/v1"),[apiKey,setApiKey]=useState(""),[apiFormat,setApiFormat]=useState("openai-chat"),[defaultModel,setDefaultModel]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch("/api/providers",{cache:"no-store"});const d=await r.json();if(r.ok)setProviders(d.providers||[]);else setNotice(d.error||"Gagal memuat provider.");}
 useEffect(()=>{void load()},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setNotice("");try{const r=await fetch("/api/providers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,baseUrl,apiKey,apiFormat,defaultModel:defaultModel||null})});const d=await r.json();if(!r.ok)throw new Error(d.error);setApiKey("");setNotice("Provider tersimpan. Jalankan Tes koneksi untuk memverifikasi API.");await load();}catch(e){setNotice(e instanceof Error?e.message:"Gagal menyimpan");}finally{setBusy(false)}}
 async function test(id:string){setNotice("Menguji koneksi...");const r=await fetch("/api/providers/"+id+"/test",{method:"POST"});const d=await r.json();setNotice(d.ok?"Terhubung. "+(d.models?.length||0)+" model ditemukan.":d.error||d.detail||"Tes gagal.");await load();}
 async function remove(id:string){if(!confirm("Hapus provider dan kredensial tersimpannya?"))return;const r=await fetch("/api/providers/"+id,{method:"DELETE"});if(r.ok){setNotice("Provider dihapus.");await load()}else setNotice("Gagal menghapus provider.");}
 return <main style={{minHeight:"100vh",background:"#080b10",color:"#eef2f7",padding:24,fontFamily:"Arial",maxWidth:1050,margin:"auto"}}><a href="/" style={{color:"#90b7ff"}}>← Kembali ke kantor</a><h1 style={{fontSize:32,marginBottom:6}}>Provider Manager</h1><p style={{color:"#99a5b5"}}>Token disimpan di server dengan enkripsi AES-256-GCM. Token tidak ditampilkan kembali.</p>
 <section style={{border:"1px solid #273244",borderRadius:16,padding:20,marginTop:22}}><h2>Tambah provider</h2><form onSubmit={save} style={{display:"grid",gap:12,gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))"}}><label>Nama provider<input required value={name} onChange={e=>setName(e.target.value)} style={input}/></label><label>Base URL<input required value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} style={input}/></label><label>API token / key<input required type="password" autoComplete="new-password" value={apiKey} onChange={e=>setApiKey(e.target.value)} style={input}/></label><label>Format API<select value={apiFormat} onChange={e=>setApiFormat(e.target.value)} style={input}><option value="openai-chat">OpenAI-compatible Chat Completions</option><option value="openai-responses">OpenAI Responses</option></select></label><label>Model default (opsional)<input value={defaultModel} onChange={e=>setDefaultModel(e.target.value)} placeholder="contoh: model-id" style={input}/></label><button disabled={busy} style={button}>{busy?"Menyimpan...":"Simpan provider"}</button></form>{notice&&<p role="status" style={{color:"#9ac7ff",whiteSpace:"pre-wrap"}}>{notice}</p>}</section>
 <h2 style={{marginTop:28}}>Provider tersimpan ({providers.length})</h2><div style={{display:"grid",gap:12}}>{providers.map(p=><article key={p.id} style={{border:"1px solid #273244",borderRadius:14,padding:16,background:"#0e141d"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><strong>{p.name}</strong><p style={{color:"#99a5b5",fontSize:13,wordBreak:"break-all"}}>{p.baseUrl}</p><small>{p.enabled?"Aktif":"Nonaktif"} · {p.models?.length||0} model tercatat · token tersimpan: {p.hasCredential?"Ya":"Tidak"}</small></div><div style={{display:"flex",gap:8,alignItems:"center"}}><button style={button} onClick={()=>test(p.id)}>Tes koneksi / model</button><button style={{...button,background:"#48262b"}} onClick={()=>remove(p.id)}>Hapus</button></div></div>{p.models?.length>0&&<p style={{fontSize:12,color:"#aebaca"}}>{p.models.map(m=>m.modelId).join(" · ")}</p>}</article>)}</div><p style={{color:"#8390a0",fontSize:12,marginTop:24}}>Keamanan: pasang autentikasi dan pembatasan akses sebelum mengekspos dashboard ke internet. Gunakan HTTPS untuk provider remote. HTTP hanya diperbolehkan untuk localhost.</p></main>
}
const input:React.CSSProperties={display:"block",width:"100%",marginTop:6,padding:11,borderRadius:8,border:"1px solid #344154",background:"#090e15",color:"#fff"};
const button:React.CSSProperties={padding:"11px 14px",border:0,borderRadius:8,background:"#c7dcff",color:"#101722",fontWeight:700,cursor:"pointer",alignSelf:"end"};
